[2025-06-28T17:28:40.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-28T17:28:40.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_etl.load_data manual__2025-06-28T17:28:31.138367+00:00 [queued]>
[2025-06-28T17:28:40.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_etl.load_data manual__2025-06-28T17:28:31.138367+00:00 [queued]>
[2025-06-28T17:28:40.275+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-28T17:28:40.281+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2025-06-28 17:28:31.138367+00:00
[2025-06-28T17:28:40.286+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-28T17:28:40.287+0000] {standard_task_runner.py:63} INFO - Started process 634 to run task
[2025-06-28T17:28:40.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_etl', 'load_data', 'manual__2025-06-28T17:28:31.138367+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/sales_etl.py', '--cfg-path', '/tmp/tmp8t4h12ox']
[2025-06-28T17:28:40.288+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask load_data
[2025-06-28T17:28:40.315+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_etl.load_data manual__2025-06-28T17:28:31.138367+00:00 [running]> on host 2c170f0bdbf7
[2025-06-28T17:28:40.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T17:28:31.138367+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T17:28:31.138367+00:00'
[2025-06-28T17:28:40.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-28T17:28:40.378+0000] {logging_mixin.py:188} INFO - Inserting 4 records into sales_summary...
[2025-06-28T17:28:40.384+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-06-28T17:28:40.389+0000] {logging_mixin.py:188} INFO - Inserting row: {'region': 'East', 'total_sales': 250}
[2025-06-28T17:28:40.390+0000] {logging_mixin.py:188} INFO - Inserting row: {'region': 'North', 'total_sales': 180}
[2025-06-28T17:28:40.390+0000] {logging_mixin.py:188} INFO - Inserting row: {'region': 'South', 'total_sales': 430}
[2025-06-28T17:28:40.390+0000] {logging_mixin.py:188} INFO - Inserting row: {'region': 'West', 'total_sales': 320}
[2025-06-28T17:28:40.391+0000] {logging_mixin.py:188} INFO - Data loaded successfully into sales_summary.
[2025-06-28T17:28:40.391+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-28T17:28:40.391+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-28T17:28:40.398+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sales_etl, task_id=load_data, run_id=manual__2025-06-28T17:28:31.138367+00:00, execution_date=20250628T172831, start_date=20250628T172840, end_date=20250628T172840
[2025-06-28T17:28:40.429+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-28T17:28:40.455+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-28T17:28:40.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
